#!/bin/sh

MAX_TIMESTAMPS=10
HIST_FILE="${XDG_CACHE_HOME:-"$HOME/.cache"}/bemenu_history"

[ ! -f "$HIST_FILE" ] && touch "$HIST_FILE"

# Input_list: list of commands names seperated by newlines.
{ IFS=:; ls --time-style=+%s -lHu $PATH | awk -v OFS='|' '$1 ~ /^(-|l).*x/ {print $7, 0, $6}'; } |
    # Input_processing: Scores are calculated and commands are sorted by thier
    # scores.
    awk -F"|" -v t="$(date +%s)" '
    BEGIN {
        OFS="|";
    }
    !cnt[$1]++ {
        score = 0;
        if ($2) {
            for (i = 3; i <= NF; i++) {
                diff = t - $i;
                if (diff <= 14400) score += 100;
                if (diff <= 86400) score += 80;
                if (diff <= 259200) score += 60;
                if (diff <= 604800) score += 40;
                if (diff <= 2419200) score += 20;
                if (diff <= 7776000) score += 10;
            }
            score = $2 * score / (NF - 2);
        }
        print $1, $3, score;
    }' "$HIST_FILE" - | sort -t'|' -k3,3rn -k2,2rn | cut -d'|' -f 1 | bemenu "$@" |
    # Output_processing: Selected command name's timestamp(recency) and launch
    # count(frequency) is updated.
    awk -F"|" -v t="$(date +%s)" -v f="$HIST_FILE" -v n="$MAX_TIMESTAMPS" '
    BEGIN {
        OFS = "|";
    }
    {
        if (FILENAME == "-") {
            is_used[$1] = 1;
            print $1;
        } else {
            if (is_used[$1]) {
                line = $1 "|" $2 + 1 "|" t;
                end = NF <= n + 1 ? NF : n + 1;
                for (i = 3; i <= end; i++)
                    line = line "|" $i;
            }
            else line = $0;
            print line > f;
            delete is_used[$1];
        }
    }
    END {
        for (c in is_used)
            print c, 1, t > f;
    }' - "$HIST_FILE" |
    # Output_launch: Launch selected commands
    while read cmd; do ${SHELL:-"/bin/bash"} -c "$cmd" & done
